"""Agregar campo documento a Noticia

Revision ID: 02d217b9c3c4
Revises: 3b06eb30d160
Create Date: 2025-11-24 00:44:05.209989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d217b9c3c4'
down_revision = '3b06eb30d160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.drop_column('documento')

    # ### end Alembic commands ###
