"""

Revision ID: 085d4756c567
Revises: 68a9613c1356
Create Date: 2026-01-03 21:53:58.876761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085d4756c567'
down_revision = '68a9613c1356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_academico', sa.String(length=100), nullable=True))
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('titulo_academico')

    # ### end Alembic commands ###
