"""Configuracion del bibliotecario

Revision ID: 093b457885c1
Revises: 2c2edc0678bf
Create Date: 2026-01-29 14:25:27.303013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093b457885c1'
down_revision = '2c2edc0678bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['biblioteca.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votos_profesores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_voto_profesor_estudiante'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votos_profesores', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_voto_profesor_estudiante'), ['estudiante_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('prestamo')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
