"""Tabla de profesores

Revision ID: 0fd639292328
Revises: 7413982b3843
Create Date: 2025-12-25 23:12:56.326179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd639292328'
down_revision = '7413982b3843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('titulo_academico', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carpeta_recursos', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('firma_digital', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_column('firma_digital')
        batch_op.drop_column('carpeta_recursos')
        batch_op.drop_column('titulo_academico')
        batch_op.drop_column('especialidad')

    # ### end Alembic commands ###
