"""cambiar ultima_conexion a datetime

Revision ID: 0fff300f4272
Revises: 855d3258a03d
Create Date: 2026-01-15 22:42:56.122249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fff300f4272'
down_revision = '855d3258a03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('ultima_conexion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True,
               # Añadimos esta línea para forzar la conversión en Postgres
               postgresql_using='ultima_conexion::timestamp without time zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('ultima_conexion',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
