"""corrigiendo relacion votos estudiantes

Revision ID: 11bed75b6037
Revises: 1cc6404eade2
Create Date: 2026-01-24 15:15:20.514307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bed75b6037'
down_revision = '1cc6404eade2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos_delegados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('candidato_nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_voto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id')
    )
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('administradores_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('asignaturas_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('biblioteca_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estudiantes_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notas_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notificaciones_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profesores_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('secretarias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('secretarias_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secretarias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('secretarias_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('profesores_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notificaciones_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notas_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estudiantes_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('biblioteca_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asignaturas_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('administradores_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    op.drop_table('votos_delegados')
    # ### end Alembic commands ###
