"""

Revision ID: 13309844686a
Revises: 4805c271e1f9
Create Date: 2025-12-28 22:43:11.333707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13309844686a'
down_revision = '4805c271e1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('mensaje',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('referencia_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referencia_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('mensaje',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
