"""Nuevos campos del perfil

Revision ID: 17cad7255c45
Revises: 
Create Date: 2025-11-26 23:17:49.754720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cad7255c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('curso', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('foto_portada', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('biografia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('debates', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('debates')
        batch_op.drop_column('biografia')
        batch_op.drop_column('telefono')
        batch_op.drop_column('foto_portada')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('curso')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
