"""

Revision ID: 1cc6404eade2
Revises: e1bf4d345e19
Create Date: 2026-01-16 23:06:28.171022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc6404eade2'
down_revision = 'e1bf4d345e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buzon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leido', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buzon', schema=None) as batch_op:
        batch_op.drop_column('leido')

    # ### end Alembic commands ###
