"""Entrando en la fase vip, Actas de la secretaria

Revision ID: 248ed497895d
Revises: 73d4e8e41bee
Create Date: 2026-01-04 16:38:09.567235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248ed497895d'
down_revision = '73d4e8e41bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretaria_actas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura', sa.String(length=150), nullable=False),
    sa.Column('codigo_asig', sa.String(length=20), nullable=True),
    sa.Column('semestre', sa.String(length=20), nullable=True),
    sa.Column('periodo_lectivo', sa.String(length=20), nullable=True),
    sa.Column('convocatoria', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('profesor_nombre', sa.String(length=150), nullable=True),
    sa.Column('recibido', sa.Boolean(), nullable=True),
    sa.Column('acta_generada', sa.Boolean(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretaria_actas')
    # ### end Alembic commands ###
