"""

Revision ID: 2c2edc0678bf
Revises: a2e98f188f9f
Create Date: 2026-01-24 15:56:30.591499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2edc0678bf'
down_revision = 'a2e98f188f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votos_delegados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidato_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'candidatos_delegado', ['candidato_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votos_delegados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('candidato_id')

    # ### end Alembic commands ###
