"""Agregando comentarios para noticias

Revision ID: 3600921256b1
Revises: 5758412ac222
Create Date: 2026-01-01 20:29:08.680131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3600921256b1'
down_revision = '5758412ac222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noticia_id', sa.Integer(), nullable=True))
        batch_op.alter_column('debate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'noticias', ['noticia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('debate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('noticia_id')

    # ### end Alembic commands ###
