"""Nuevas columnas para matricula

Revision ID: 36bb772a8b1b
Revises: a514358aa01f
Create Date: 2025-12-23 20:24:16.148341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bb772a8b1b'
down_revision = 'a514358aa01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        # Añadimos server_default para que las filas existentes se llenen automáticamente
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=False, server_default='Masculino'))
        batch_op.add_column(sa.Column('nacionalidad', sa.String(length=100), nullable=False, server_default='Guineana'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.drop_column('nacionalidad')
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
