"""Agregar destacado a Noticia

Revision ID: 3b06eb30d160
Revises: 
Create Date: 2025-11-22 22:01:09.527288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b06eb30d160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('creado_por', sa.String(length=255), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('visible_para')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('hora',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('eventos_creador_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enviado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recibido', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mensaje_favorito', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archivo_adjunto', sa.String(length=255), nullable=True))

    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('archivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tipo_archivo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pie_archivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('enlace_programa', sa.String(length=255), nullable=True))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('autor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('noticias_autor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['autor_id'], ['id'])
        batch_op.drop_column('fecha_publicacion')
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_publicacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('noticias_autor_id_fkey'), 'usuarios', ['autor_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('autor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('enlace_programa')
        batch_op.drop_column('pie_archivo')
        batch_op.drop_column('tipo_archivo')
        batch_op.drop_column('archivo')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_column('archivo_adjunto')
        batch_op.drop_column('mensaje_favorito')
        batch_op.drop_column('recibido')
        batch_op.drop_column('enviado')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('eventos_creador_id_fkey'), 'usuarios', ['creador_id'], ['id'])
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('hora',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('calendario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_para', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('creado_por')
        batch_op.drop_column('hora')

    # ### end Alembic commands ###
