"""Recuperar contrasenas Usuarios

Revision ID: 3e041f53aaa0
Revises: edfb20d1c68d
Create Date: 2026-01-13 11:55:34.802222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e041f53aaa0'
down_revision = 'edfb20d1c68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('recovery_expire', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('recovery_expire')
        batch_op.drop_column('recovery_code')

    # ### end Alembic commands ###
