"""Anuncios directivos

Revision ID: 3f68ed701810
Revises: d55d6b140ac0
Create Date: 2026-01-07 23:48:48.696623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f68ed701810'
down_revision = 'd55d6b140ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncios_directivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('directivo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('archivo_adjunto', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['directivo_id'], ['directivos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anuncios_directivos')
    # ### end Alembic commands ###
