"""Titulacion agregada a la Biblioteca

Revision ID: 425ee378bf24
Revises: 8fbb1c2b4b4f
Create Date: 2025-12-01 22:48:45.897207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ee378bf24'
down_revision = '8fbb1c2b4b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulacion', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.drop_column('titulacion')

    # ### end Alembic commands ###
