"""Creando rol secretaria

Revision ID: 43b575dc5d3e
Revises: b769cba4eea5
Create Date: 2026-01-07 22:10:04.600727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b575dc5d3e'
down_revision = 'b769cba4eea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre_secretaria', sa.String(length=100), nullable=False),
    sa.Column('apellidos_secretaria', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('correo_personal', sa.String(length=100), nullable=True),
    sa.Column('correo_institucional', sa.String(length=100), nullable=False),
    sa.Column('dip_secretaria', sa.String(length=20), nullable=False),
    sa.Column('telefono_secretaria', sa.String(length=20), nullable=False),
    sa.Column('decano', sa.String(length=20), nullable=False),
    sa.Column('archivos', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretaria')
    # ### end Alembic commands ###
