"""buzon agregado para activar cuenta

Revision ID: 46851014acdb
Revises: 248ed497895d
Create Date: 2026-01-05 17:30:47.293019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46851014acdb'
down_revision = '248ed497895d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensaje_buzon', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.drop_column('mensaje_buzon')

    # ### end Alembic commands ###
