"""

Revision ID: 4805c271e1f9
Revises: c0f7b6d5fa18
Create Date: 2025-12-28 21:31:14.690324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4805c271e1f9'
down_revision = 'c0f7b6d5fa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
