"""Nuevas actualizaciones para el registro

Revision ID: 4b66f4853031
Revises: ccae2711df48
Create Date: 2025-12-24 14:14:52.803095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b66f4853031'
down_revision = 'ccae2711df48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulacion_autorizada', sa.String(length=100), nullable=False))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrera', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('carrera')

    with op.batch_alter_table('codigos_estudiantes', schema=None) as batch_op:
        batch_op.drop_column('titulacion_autorizada')

    # ### end Alembic commands ###
