"""Mi calendario

Revision ID: 4d955a8d3522
Revises: 6fec5871839a
Create Date: 2025-12-16 00:04:52.596849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d955a8d3522'
down_revision = '6fec5871839a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calendario')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('hora')
        batch_op.drop_column('fecha')
        batch_op.drop_column('creador_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creador_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('all_day')
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('titulo')

    op.create_table('calendario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('calendario_pkey'))
    )
    op.drop_table('anuncios')
    # ### end Alembic commands ###
