"""

Revision ID: 4f58654a2937
Revises: 3f68ed701810
Create Date: 2026-01-08 10:26:46.046749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f58654a2937'
down_revision = '3f68ed701810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios_directivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alcance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anuncios_directivos', schema=None) as batch_op:
        batch_op.drop_column('alcance')

    # ### end Alembic commands ###
