"""

Revision ID: 4fb5e1244d96
Revises: 11bed75b6037
Create Date: 2026-01-24 15:43:04.031105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fb5e1244d96'
down_revision = '11bed75b6037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos_delegado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('lema', sa.String(length=200), nullable=False),
    sa.Column('fecha_postulacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id')
    )
    op.create_table('propuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos_profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_voto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', name='unique_voto_profesor_estudiante')
    )
    op.drop_table('votos_delegados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos_delegados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidato_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_voto', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name=op.f('votos_delegados_estudiante_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('votos_delegados_pkey')),
    sa.UniqueConstraint('estudiante_id', name=op.f('votos_delegados_estudiante_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('votos_profesores')
    op.drop_table('propuestas')
    op.drop_table('candidatos_delegado')
    # ### end Alembic commands ###
