"""Agregando mas datos a alumnos y profesores

Revision ID: 5c796e237d7d
Revises: 085d4756c567
Create Date: 2026-01-04 14:28:35.756132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c796e237d7d'
down_revision = '085d4756c567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naturalde_aspirante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provinciadistrito_aspirante', sa.String(length=100), nullable=True))

    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distrito_provincia', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.drop_column('distrito_provincia')

    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_column('provinciadistrito_aspirante')
        batch_op.drop_column('naturalde_aspirante')

    # ### end Alembic commands ###
