"""Talento agregado a Usuarios

Revision ID: 600bac64184a
Revises: 6f18a32eb554
Create Date: 2025-12-25 16:16:05.877081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600bac64184a'
down_revision = '6f18a32eb554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buzon', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('mensaje',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('talento')

    with op.batch_alter_table('buzon', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
