"""Tabla expediente

Revision ID: 663ec419bcee
Revises: 600bac64184a
Create Date: 2025-12-25 19:30:09.529239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '663ec419bcee'
down_revision = '600bac64184a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('asignatura_nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('asignatura_codigo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('creditos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nota_final', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('convocatoria', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semestre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('anio_academico', sa.String(length=10), nullable=True))
        batch_op.drop_constraint(batch_op.f('expedientes_estudiante_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('nombre_documento')
        batch_op.drop_column('tipo')
        batch_op.drop_column('fecha_subida')
        batch_op.drop_column('ruta_archivo')
        batch_op.drop_column('estudiante_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ruta_archivo', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_subida', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_documento', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expedientes_estudiante_id_fkey'), 'estudiantes', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('anio_academico')
        batch_op.drop_column('semestre')
        batch_op.drop_column('convocatoria')
        batch_op.drop_column('nota_final')
        batch_op.drop_column('creditos')
        batch_op.drop_column('asignatura_codigo')
        batch_op.drop_column('asignatura_nombre')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
