"""Profesor entregar actas

Revision ID: 68a9613c1356
Revises: b7d9589a07f7
Create Date: 2026-01-03 20:02:52.325471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a9613c1356'
down_revision = 'b7d9589a07f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregas_oficiales_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_column('entregas_oficiales_json')

    # ### end Alembic commands ###
