"""Donde envian reportes

Revision ID: 68cc6b67a706
Revises: d7a74033799d
Create Date: 2026-01-10 16:03:40.768375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cc6b67a706'
down_revision = 'd7a74033799d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_recibidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=200), nullable=True),
    sa.Column('remitente_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_recibidos')
    # ### end Alembic commands ###
