"""Modificando el buzon

Revision ID: 6f18a32eb554
Revises: 99ff179219ce
Create Date: 2025-12-24 20:24:28.970371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f18a32eb554'
down_revision = '99ff179219ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buzon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_consulta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dip', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buzon', schema=None) as batch_op:
        batch_op.drop_column('dip')
        batch_op.drop_column('tipo_consulta')

    # ### end Alembic commands ###
