"""

Revision ID: 730dc5796db6
Revises: f397fbe2ae0e
Create Date: 2025-12-28 13:17:34.072989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '730dc5796db6'
down_revision = 'f397fbe2ae0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('asignatura', sa.String(length=150), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notas_personales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_personales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asignatura', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('creditos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('notas_personales_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notas_personales_pkey'))
    )
    op.drop_table('notas')
    # ### end Alembic commands ###
