"""

Revision ID: 73d4e8e41bee
Revises: 5c796e237d7d
Create Date: 2026-01-04 15:05:50.557130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d4e8e41bee'
down_revision = '5c796e237d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('natural_de', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('distrito_provincia', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('distrito_provincia')
        batch_op.drop_column('natural_de')

    # ### end Alembic commands ###
