"""Migracion base de creacion de todas las tablas

Revision ID: 7a21bdcd3e4e
Revises: 
Create Date: 2025-12-10 01:10:06.584468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a21bdcd3e4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('creado_por', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codigos_estudiante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codigos_estudiante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codigos_estudiante_codigo'), ['codigo'], unique=True)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True),
    sa.Column('foto_portada', sa.PickleType(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('residencia', sa.String(length=100), nullable=True),
    sa.Column('notificaciones_activas', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('permisos_especiales', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('biblioteca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('enlace', sa.String(length=1000), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_libro', sa.String(length=10), nullable=False),
    sa.Column('portada', sa.String(length=300), nullable=True),
    sa.Column('titulacion', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.Column('recibido', sa.Boolean(), nullable=True),
    sa.Column('mensaje_favorito', sa.Boolean(), nullable=True),
    sa.Column('archivo_adjunto', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=10), nullable=True),
    sa.Column('pie_archivo', sa.String(length=255), nullable=True),
    sa.Column('enlace_programa', sa.String(length=255), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=True),
    sa.Column('documento', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asignaturas_codigo'), ['codigo'], unique=True)

    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('carrera', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('grupo', sa.String(length=20), nullable=True),
    sa.Column('estado_academico', sa.String(length=20), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['profesores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('estudiante_asignatura',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignaturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('nombre_documento', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ruta_archivo', sa.Text(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignaturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('expedientes')
    op.drop_table('estudiante_asignatura')
    op.drop_table('estudiantes')
    op.drop_table('comentarios')
    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asignaturas_codigo'))

    op.drop_table('asignaturas')
    op.drop_table('profesores')
    op.drop_table('notificaciones')
    op.drop_table('noticias')
    op.drop_table('mensajes')
    op.drop_table('directivos')
    op.drop_table('debates')
    op.drop_table('biblioteca')
    op.drop_table('administradores')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    op.drop_table('matriculas')
    op.drop_table('eventos')
    with op.batch_alter_table('codigos_estudiante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codigos_estudiante_codigo'))

    op.drop_table('codigos_estudiante')
    op.drop_table('calendario')
    # ### end Alembic commands ###
