"""Matricula actualizada

Revision ID: 7fc3f23ad0be
Revises: 95a4e54e09f0
Create Date: 2025-12-22 15:41:03.208097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc3f23ad0be'
down_revision = '95a4e54e09f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_ficha_matricula', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_ficha_permanencia', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.drop_column('doc_ficha_permanencia')
        batch_op.drop_column('doc_ficha_matricula')

    # ### end Alembic commands ###
