"""Ultima coneccion (ultima vez usuarios)

Revision ID: 855d3258a03d
Revises: 3e041f53aaa0
Create Date: 2026-01-15 22:37:57.546421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d3258a03d'
down_revision = '3e041f53aaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_conexion', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ultima_conexion')

    # ### end Alembic commands ###
