"""Poner tipo_libro en Biblioteca

Revision ID: 8b2e5e8cd684
Revises: f7d99b0ef02d
Create Date: 2025-11-30 17:40:54.982935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2e5e8cd684'
down_revision = 'f7d99b0ef02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_libro', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biblioteca', schema=None) as batch_op:
        batch_op.drop_column('tipo_libro')

    # ### end Alembic commands ###
