"""Tabla de matricula hecha

Revision ID: 95a4e54e09f0
Revises: d1957ba00106
Create Date: 2025-12-21 21:29:24.019133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a4e54e09f0'
down_revision = 'd1957ba00106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_estudiante', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('residencia', sa.String(length=200), nullable=False),
    sa.Column('natural_de', sa.String(length=100), nullable=False),
    sa.Column('dni_numero', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('doc_dni', sa.String(length=255), nullable=True),
    sa.Column('doc_cert_selectividad', sa.String(length=255), nullable=True),
    sa.Column('doc_instancia', sa.String(length=255), nullable=True),
    sa.Column('doc_hoja_bachillerato', sa.String(length=255), nullable=True),
    sa.Column('doc_foto_carnet', sa.String(length=255), nullable=True),
    sa.Column('doc_conducta_comunidad', sa.String(length=255), nullable=True),
    sa.Column('doc_conducta_centro', sa.String(length=255), nullable=True),
    sa.Column('doc_hoja_facultad', sa.String(length=255), nullable=True),
    sa.Column('doc_acta_defensa', sa.String(length=255), nullable=True),
    sa.Column('doc_convalidaciones', sa.String(length=255), nullable=True),
    sa.Column('doc_homologacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_matricula')
    # ### end Alembic commands ###
