"""Sistema de registro

Revision ID: 99ff179219ce
Revises: 4b66f4853031
Create Date: 2025-12-24 15:37:00.306762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ff179219ce'
down_revision = '4b66f4853031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
