"""

Revision ID: 9b304ad1396f
Revises: ca954d8f072d
Create Date: 2025-12-28 16:26:01.784977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b304ad1396f'
down_revision = 'ca954d8f072d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reaccion', sa.String(length=20), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('contenido',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('creditos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creditos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('contenido',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('reaccion')
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
