"""

Revision ID: a2e98f188f9f
Revises: 4fb5e1244d96
Create Date: 2026-01-24 15:51:26.368737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e98f188f9f'
down_revision = '4fb5e1244d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos_delegados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('candidato_nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_voto', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos_delegados')
    # ### end Alembic commands ###
