"""Matricula completa

Revision ID: a514358aa01f
Revises: 7fc3f23ad0be
Create Date: 2025-12-22 20:47:44.346350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a514358aa01f'
down_revision = '7fc3f23ad0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrera', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('observaciones_admin', sa.Text(), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('observaciones_admin')
        batch_op.drop_column('telefono')
        batch_op.drop_column('carrera')

    # ### end Alembic commands ###
