"""

Revision ID: a9cac517f068
Revises: 43b575dc5d3e
Create Date: 2026-01-07 22:12:32.925437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cac517f068'
down_revision = '43b575dc5d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secretaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secretaria', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
