"""Actualizando las Notas

Revision ID: b30ade53028d
Revises: 0af6ba178d4a
Create Date: 2025-12-31 17:30:03.644733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30ade53028d'
down_revision = '0af6ba178d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semestre', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_column('semestre')

    # ### end Alembic commands ###
