"""Construyendo al directivo

Revision ID: b3368ca085d4
Revises: e23a72ba2943
Create Date: 2025-12-27 00:30:52.655892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3368ca085d4'
down_revision = 'e23a72ba2943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facultad', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('firma_digital', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directivos', schema=None) as batch_op:
        batch_op.drop_column('firma_digital')
        batch_op.drop_column('facultad')

    # ### end Alembic commands ###
