"""

Revision ID: b4ade9e5c718
Revises: e31d3b812e5e
Create Date: 2025-12-25 21:53:00.834164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ade9e5c718'
down_revision = 'e31d3b812e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profesores', ['tutor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tutor_id')

    # ### end Alembic commands ###
