"""Subida de archivos por carpetas

Revision ID: b769cba4eea5
Revises: 46851014acdb
Create Date: 2026-01-07 21:05:00.578522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b769cba4eea5'
down_revision = '46851014acdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('carpeta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carpeta_id'], ['carpeta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_archivo')
    op.drop_table('carpeta')
    # ### end Alembic commands ###
