"""Empezando agragar nuevas funciones para el profesor

Revision ID: b7d9589a07f7
Revises: 3600921256b1
Create Date: 2026-01-03 18:16:40.131659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d9589a07f7'
down_revision = '3600921256b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mis_documentos_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_column('mis_documentos_json')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
