"""

Revision ID: c0f7b6d5fa18
Revises: 9b304ad1396f
Create Date: 2025-12-28 16:41:59.458588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f7b6d5fa18'
down_revision = '9b304ad1396f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creditos', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_asignaturas_codigo'))
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_asignaturas_codigo'), ['codigo'], unique=True)
        batch_op.drop_column('creditos')

    # ### end Alembic commands ###
