"""Control disciplinario en funciones

Revision ID: c4f4243a2b85
Revises: 4f58654a2937
Create Date: 2026-01-08 11:51:21.304553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f4243a2b85'
down_revision = '4f58654a2937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_expiracion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_suspension', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('motivo_suspension')
        batch_op.drop_column('fecha_expiracion')
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
