"""

Revision ID: ca954d8f072d
Revises: 730dc5796db6
Create Date: 2025-12-28 15:24:35.742216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca954d8f072d'
down_revision = '730dc5796db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudiante_asignatura')
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignatura_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'asignaturas', ['asignatura_id'], ['id'])
        batch_op.drop_column('asignatura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignatura', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asignatura_id')

    op.create_table('estudiante_asignatura',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asignatura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inscripcion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignaturas.id'], name=op.f('estudiante_asignatura_asignatura_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name=op.f('estudiante_asignatura_estudiante_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('estudiante_asignatura_pkey'))
    )
    # ### end Alembic commands ###
