"""Sistema de usuarios actualizado con codigo de estudiante

Revision ID: ccae2711df48
Revises: 36bb772a8b1b
Create Date: 2025-12-24 12:54:31.723704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccae2711df48'
down_revision = '36bb772a8b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('estudiante_dip', sa.String(length=20), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.drop_table('matriculas')
    with op.batch_alter_table('codigos_estudiante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codigos_estudiante_codigo'))

    op.drop_table('codigos_estudiante')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('debate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correo_institucional', sa.String(length=150), nullable=True))
        batch_op.alter_column('dip',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['dip'])
        batch_op.create_unique_constraint(None, ['correo_institucional'])
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('dip',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('correo_institucional')
        batch_op.drop_column('debate')
        batch_op.drop_column('apellidos')

    op.create_table('codigos_estudiante',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('usado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('codigos_estudiante_pkey'))
    )
    with op.batch_alter_table('codigos_estudiante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codigos_estudiante_codigo'), ['codigo'], unique=True)

    op.create_table('matriculas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('carrera', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('matriculas_pkey')),
    sa.UniqueConstraint('correo', name=op.f('matriculas_correo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('codigos_estudiantes')
    # ### end Alembic commands ###
