"""Selectividad y conjuntos agregados

Revision ID: d1957ba00106
Revises: 3c235eda4849
Create Date: 2025-12-19 23:31:29.962534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1957ba00106'
down_revision = '3c235eda4849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selectividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('comentario_admin', sa.Text(), nullable=True),
    sa.Column('ruta_pdf', sa.String(length=255), nullable=False),
    sa.Column('ruta_foto', sa.String(length=255), nullable=True),
    sa.Column('ruta_pie_foto', sa.String(length=255), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opiniones_selectividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('selectividad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selectividad_id'], ['selectividad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opiniones_selectividad')
    op.drop_table('selectividad')
    # ### end Alembic commands ###
