"""

Revision ID: d55d6b140ac0
Revises: a9cac517f068
Create Date: 2026-01-07 22:20:13.173385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55d6b140ac0'
down_revision = 'a9cac517f068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre_secretaria', sa.String(length=100), nullable=False),
    sa.Column('apellidos_secretaria', sa.String(length=100), nullable=False),
    sa.Column('foto_perfil', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('correo_personal', sa.String(length=100), nullable=True),
    sa.Column('correo_institucional', sa.String(length=100), nullable=False),
    sa.Column('dip_secretaria', sa.String(length=20), nullable=False),
    sa.Column('telefono_secretaria', sa.String(length=20), nullable=False),
    sa.Column('decano', sa.String(length=20), nullable=False),
    sa.Column('archivos', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('secretaria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretaria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_secretaria', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos_secretaria', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('departamento', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo_personal', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('correo_institucional', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dip_secretaria', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('telefono_secretaria', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('decano', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('archivos', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('foto_perfil', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('secretaria_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('secretaria_pkey'))
    )
    op.drop_table('secretarias')
    # ### end Alembic commands ###
