"""Proteccion de carpetas

Revision ID: d7a74033799d
Revises: c4f4243a2b85
Create Date: 2026-01-10 15:20:15.518977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a74033799d'
down_revision = 'c4f4243a2b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carpeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creador_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('es_publica', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['creador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carpeta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('es_publica')
        batch_op.drop_column('creador_id')

    # ### end Alembic commands ###
