"""Construyendo el registro para profesores

Revision ID: e23a72ba2943
Revises: 0fd639292328
Create Date: 2025-12-26 12:45:46.319823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23a72ba2943'
down_revision = '0fd639292328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_dip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('archivo_foto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('codigo_activacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cuenta_activa', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['codigo_activacion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cuenta_activa')
        batch_op.drop_column('codigo_activacion')
        batch_op.drop_column('archivo_foto')
        batch_op.drop_column('archivo_dip')

    # ### end Alembic commands ###
