"""Cosas de expedientes

Revision ID: e31d3b812e5e
Revises: 663ec419bcee
Create Date: 2025-12-25 21:46:47.869496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e31d3b812e5e'
down_revision = '663ec419bcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('estudiantes_matricula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('estudiantes_tutor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('estudiantes_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('carrera')
        batch_op.drop_column('semestre')
        batch_op.drop_column('tutor_id')
        batch_op.drop_column('fecha_ingreso')
        batch_op.drop_column('estado_academico')
        batch_op.drop_column('grupo')

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estudiante_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('firmado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_firma', sa.DateTime(), nullable=True))
        batch_op.alter_column('anio_academico',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('expedientes_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estudiantes', ['estudiante_id'], ['id'])
        batch_op.drop_column('semestre')
        batch_op.drop_column('convocatoria')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('creditos')
        batch_op.drop_column('asignatura_codigo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignatura_codigo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('creditos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('convocatoria', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semestre', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expedientes_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.alter_column('anio_academico',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('fecha_firma')
        batch_op.drop_column('firmado')
        batch_op.drop_column('estudiante_id')

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado_academico', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_ingreso', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semestre', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carrera', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estudiantes_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('estudiantes_tutor_id_fkey'), 'profesores', ['tutor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint(batch_op.f('estudiantes_matricula_key'), ['matricula'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('matricula',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
