"""Actualizando profesores

Revision ID: eb4cac013d84
Revises: b3368ca085d4
Create Date: 2025-12-27 18:25:50.245450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb4cac013d84'
down_revision = 'b3368ca085d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_aspirante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('apellidos_aspirante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('correo_personal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dip_aspirante', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefono_aspirante', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sexo_aspirante', sa.String(length=20), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('departamento',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('profesores_codigo_activacion_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('profesores_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('fecha_ingreso')
        batch_op.drop_column('carpeta_recursos')
        batch_op.drop_column('titulo_academico')
        batch_op.drop_column('firma_digital')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_digital', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo_academico', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carpeta_recursos', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_ingreso', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('profesores_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('profesores_codigo_activacion_key'), ['codigo_activacion'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('departamento',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('sexo_aspirante')
        batch_op.drop_column('telefono_aspirante')
        batch_op.drop_column('dip_aspirante')
        batch_op.drop_column('correo_personal')
        batch_op.drop_column('apellidos_aspirante')
        batch_op.drop_column('nombre_aspirante')

    # ### end Alembic commands ###
