"""Eliminación de campo en Directivo

Revision ID: ebedc9248575
Revises: 425ee378bf24
Create Date: 2025-12-10 00:32:48.114654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebedc9248575'
down_revision = '425ee378bf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directivos', schema=None) as batch_op:
        batch_op.drop_column('fecha_ingreso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ingreso', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
