"""Editar perfil del directivo

Revision ID: edfb20d1c68d
Revises: f366864d8d95
Create Date: 2026-01-11 17:34:38.818430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfb20d1c68d'
down_revision = 'f366864d8d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seccion', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=255), nullable=True))
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('facultad')
        batch_op.drop_column('firma_digital')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_digital', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('facultad', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('ubicacion')
        batch_op.drop_column('seccion')

    # ### end Alembic commands ###
