"""

Revision ID: f366864d8d95
Revises: 68cc6b67a706
Create Date: 2026-01-11 16:35:18.232437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f366864d8d95'
down_revision = '68cc6b67a706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_recibidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_recibidos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
