"""Creando notas para estudiantes

Revision ID: f397fbe2ae0e
Revises: eb4cac013d84
Create Date: 2025-12-28 13:08:34.630908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f397fbe2ae0e'
down_revision = 'eb4cac013d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('asignatura', sa.String(length=150), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asignatura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignaturas.id'], name=op.f('notas_asignatura_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name=op.f('notas_estudiante_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notas_pkey'))
    )
    op.drop_table('notas_personales')
    # ### end Alembic commands ###
