"""Clase biblioteca agregada

Revision ID: f7d99b0ef02d
Revises: b7709f6aed30
Create Date: 2025-11-30 13:40:24.813909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d99b0ef02d'
down_revision = 'b7709f6aed30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblioteca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('enlace', sa.String(length=1000), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biblioteca')
    # ### end Alembic commands ###
